version: '3'
services:
  restapp:
    container_name: appTsungMin146
    image: java:8
    ports:
      - "80:8080"
    working_dir: /rest
    volumes:
      - ./restapp:/rest
    links:
      - mongodb
    networks: 
      - rest-nosql
    command: java -jar cmpe282tsungmin146.jar --spring.config.location="file:/application.properties"

  mongodb:
    container_name: dbTsungMin146
    image: mongo:3.4.9
    networks: 
      rest-nosql:
        aliases:
          - dbTsungMin146
          # application.properties uri ignore case 
          - dbtsungmin146

networks: 
  rest-nosql: 